
module.exports = {
    ActionTypes: {
        ROUTE_SHOW: 'ROUTE_SHOW',
        ROUTE_HIDE: 'ROUTE_HIDE',
        RECEIVE_RAW_ROUTES: 'RECEIVE_RAW_ROUTES',
        RECEIVE_RAW_STOPS: 'RECEIVE_RAW_STOPS',
        RECEIVE_RAW_POLYLINES: 'RECEIVE_RAW_POLYLINES',
        RECEIVE_RAW_VEHICLES: 'RECEIVE_RAW_VEHICLES',
    },
    PayloadSources: {
        SERVER_ACTION: 'SERVER_ACTION',
        VIEW_ACTION: 'VIEW_ACTION',
    }
};
